# Generated by Django 2.0.3 on 2018-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180404_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
