# Generated by Django 2.0.3 on 2018-04-09 20:07

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180405_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=200, unique=True),
        ),
    ]
