# Generated by Django 2.0.3 on 2018-04-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180409_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post.id', max_length=200, unique=True),
        ),
    ]
