# Generated by Django 2.0.3 on 2018-04-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='This user likes to keep an air of mystery about them.', max_length=500)),
                ('location', models.CharField(blank=True, default='???', max_length=30)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='img/profiles')),
                ('house_number', models.CharField(max_length=20, verbose_name='House number/name *')),
                ('address1', models.CharField(max_length=60, verbose_name='Street *')),
                ('address2', models.CharField(blank=True, max_length=60, verbose_name='Secondary address line')),
                ('city', models.CharField(max_length=20, verbose_name='Town/City *')),
                ('county', models.CharField(max_length=30, verbose_name='County/State/Province *')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post/Zip Code *')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
