# Generated by Django 2.0.3 on 2018-03-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180329_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/img/accounts/profile_default.png', null=True, upload_to='img/profiles'),
        ),
    ]
