# Generated by Django 2.0.3 on 2018-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180403_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(help_text='Please enter your street.', max_length=60, verbose_name='Street *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(help_text='Please enter your town or city.', max_length=20, verbose_name='Town/City *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(help_text='Please enter your county or state.', max_length=30, verbose_name='County/State/Province *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.CharField(help_text='Please enter your house number.', max_length=20, verbose_name='House number/name *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.CharField(help_text='Please enter your postal or zip code.', max_length=10, verbose_name='Post/Zip Code *'),
        ),
    ]
