# Generated by Django 2.0.3 on 2018-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180403_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(max_length=60, verbose_name='Street *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Town/City *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(max_length=30, verbose_name='County/State/Province *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='House number/name *'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.CharField(max_length=10, verbose_name='Post/Zip Code *'),
        ),
    ]
